#!/bin/bash

# ═══════════════════════════════════════════════════════════════════════════
# Dotfiles Setup Wizard
# Run this first to configure your dotfiles before installation
# ═══════════════════════════════════════════════════════════════════════════

set -e

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$DOTFILES_DIR/config.local"

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║              🚀 Dotfiles Setup Wizard                         ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

# Check if config already exists
if [ -f "$CONFIG_FILE" ]; then
    echo "⚠️  config.local already exists."
    read -p "   Overwrite? (y/N): " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        echo "   Keeping existing config. Run ./install.sh to continue."
        exit 0
    fi
fi

echo "Let's configure your dotfiles..."
echo ""

# ===== User Info =====
echo "📝 Git Configuration"
echo "─────────────────────"
read -p "   Your name: " git_name
read -p "   Your email: " git_email
echo ""

# ===== Editor =====
echo "📝 Default Editor"
echo "─────────────────────"
echo "   Options: cursor, code, zed, vim, nvim"
read -p "   Editor [cursor]: " editor
editor=${editor:-cursor}
echo ""

# ===== Node.js =====
echo "📝 Node.js Version"
echo "─────────────────────"
read -p "   Version [20]: " node_version
node_version=${node_version:-20}
echo ""

# ===== Optional Tools =====
echo "📝 Optional Tools"
echo "─────────────────────"
read -p "   Install DDEV (PHP development)? (Y/n): " install_ddev
install_ddev=${install_ddev:-Y}
[[ "$install_ddev" =~ ^[Yy]$ ]] && install_ddev="true" || install_ddev="false"

read -p "   Install OrbStack (Docker)? (Y/n): " install_orbstack
install_orbstack=${install_orbstack:-Y}
[[ "$install_orbstack" =~ ^[Yy]$ ]] && install_orbstack="true" || install_orbstack="false"
echo ""

# ===== macOS Settings =====
echo "📝 macOS Settings"
echo "─────────────────────"
read -p "   Show hidden files in Finder? (Y/n): " macos_hidden
macos_hidden=${macos_hidden:-Y}
[[ "$macos_hidden" =~ ^[Yy]$ ]] && macos_hidden="true" || macos_hidden="false"

read -p "   Auto-hide Dock? (Y/n): " macos_dock
macos_dock=${macos_dock:-Y}
[[ "$macos_dock" =~ ^[Yy]$ ]] && macos_dock="true" || macos_dock="false"

read -p "   Fast key repeat? (Y/n): " macos_keyrepeat
macos_keyrepeat=${macos_keyrepeat:-Y}
[[ "$macos_keyrepeat" =~ ^[Yy]$ ]] && macos_keyrepeat="true" || macos_keyrepeat="false"

read -p "   Tap to click on trackpad? (Y/n): " macos_tap
macos_tap=${macos_tap:-Y}
[[ "$macos_tap" =~ ^[Yy]$ ]] && macos_tap="true" || macos_tap="false"

read -p "   Screenshots folder [$HOME/Pictures/Screenshots]: " screenshots_dir
screenshots_dir=${screenshots_dir:-$HOME/Pictures/Screenshots}
echo ""

# ===== Write config =====
echo "💾 Saving configuration..."

cat > "$CONFIG_FILE" << EOF
# Dotfiles Configuration
# Generated by setup.sh on $(date)

# ===== User Info =====
GIT_USER_NAME="$git_name"
GIT_USER_EMAIL="$git_email"

# ===== Editor =====
DEFAULT_EDITOR="$editor"

# ===== Node.js Version =====
NODE_VERSION="$node_version"

# ===== Optional Tools =====
INSTALL_DDEV="$install_ddev"
INSTALL_ORBSTACK="$install_orbstack"

# ===== macOS Settings =====
MACOS_SHOW_HIDDEN_FILES="$macos_hidden"
MACOS_DOCK_AUTOHIDE="$macos_dock"
MACOS_FAST_KEY_REPEAT="$macos_keyrepeat"
MACOS_TAP_TO_CLICK="$macos_tap"
MACOS_SCREENSHOTS_LOCATION="$screenshots_dir"

# ===== SSH =====
SSH_KEY_EMAIL="$git_email"
EOF

echo ""
echo "✅ Configuration saved to config.local"
echo ""
echo "Next steps:"
echo "  1. Review config.local if needed"
echo "  2. Run: ./install.sh"
echo ""
